import random

# TASK 1
user_input = int(input("Please introduce a number between 1 to 10: "))
generated_number = random.randint(1, 10)
if user_input == generated_number:
    print("You guessed the number!")
else:
    print("You didn't guess the number.")
print(f"You're input was {user_input}, and {generated_number} was generated by the computer.")

# TASK 2
your_name = input("Please add your name here: ")
your_age = int(input("And also your age here: "))
print(f"Hello {your_name}, on your next birthday you'll be {your_age + 1} years")

# TASK 3
user_input = list(input("Please insert your string here: "))
for i in range(5):
    random.shuffle(user_input)
    print("".join(user_input))

# TASK 4
user_input = int(input("What is the answer (insert an integer): 5 * 2 + 7 / 3 - 5 = "))
value = int(5 * 2 + 7 / 3 - 5)
if user_input == value:
    print(f"You're right it is {value}")
else:
    print(f"Quite mistaken, it is {value}")
